// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/scheduler.proto

package schedulerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Appointment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DoctorId       string                 `protobuf:"bytes,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DoctorName     string                 `protobuf:"bytes,3,opt,name=doctor_name,json=doctorName,proto3" json:"doctor_name,omitempty"`
	StartTimeUnix  int64                  `protobuf:"varint,4,opt,name=start_time_unix,json=startTimeUnix,proto3" json:"start_time_unix,omitempty"` // slot start as Unix seconds
	DurationSlots  int32                  `protobuf:"varint,5,opt,name=duration_slots,json=durationSlots,proto3" json:"duration_slots,omitempty"`   // 1 or 2 (15 or 30 min)
	PatientName    string                 `protobuf:"bytes,6,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	PatientContact string                 `protobuf:"bytes,7,opt,name=patient_contact,json=patientContact,proto3" json:"patient_contact,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *Appointment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Appointment) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *Appointment) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *Appointment) GetStartTimeUnix() int64 {
	if x != nil {
		return x.StartTimeUnix
	}
	return 0
}

func (x *Appointment) GetDurationSlots() int32 {
	if x != nil {
		return x.DurationSlots
	}
	return 0
}

func (x *Appointment) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *Appointment) GetPatientContact() string {
	if x != nil {
		return x.PatientContact
	}
	return ""
}

type CreateAppointmentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DoctorId       string                 `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DoctorName     string                 `protobuf:"bytes,2,opt,name=doctor_name,json=doctorName,proto3" json:"doctor_name,omitempty"`
	StartTimeUnix  int64                  `protobuf:"varint,3,opt,name=start_time_unix,json=startTimeUnix,proto3" json:"start_time_unix,omitempty"`
	DurationSlots  int32                  `protobuf:"varint,4,opt,name=duration_slots,json=durationSlots,proto3" json:"duration_slots,omitempty"`
	PatientName    string                 `protobuf:"bytes,5,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	PatientContact string                 `protobuf:"bytes,6,opt,name=patient_contact,json=patientContact,proto3" json:"patient_contact,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAppointmentRequest) Reset() {
	*x = CreateAppointmentRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentRequest) ProtoMessage() {}

func (x *CreateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAppointmentRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *CreateAppointmentRequest) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *CreateAppointmentRequest) GetStartTimeUnix() int64 {
	if x != nil {
		return x.StartTimeUnix
	}
	return 0
}

func (x *CreateAppointmentRequest) GetDurationSlots() int32 {
	if x != nil {
		return x.DurationSlots
	}
	return 0
}

func (x *CreateAppointmentRequest) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *CreateAppointmentRequest) GetPatientContact() string {
	if x != nil {
		return x.PatientContact
	}
	return ""
}

type ListAppointmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromTimeUnix  int64                  `protobuf:"varint,1,opt,name=from_time_unix,json=fromTimeUnix,proto3" json:"from_time_unix,omitempty"` // inclusive start of range
	ToTimeUnix    int64                  `protobuf:"varint,2,opt,name=to_time_unix,json=toTimeUnix,proto3" json:"to_time_unix,omitempty"`       // exclusive end of range
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsRequest) Reset() {
	*x = ListAppointmentsRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsRequest) ProtoMessage() {}

func (x *ListAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *ListAppointmentsRequest) GetFromTimeUnix() int64 {
	if x != nil {
		return x.FromTimeUnix
	}
	return 0
}

func (x *ListAppointmentsRequest) GetToTimeUnix() int64 {
	if x != nil {
		return x.ToTimeUnix
	}
	return 0
}

type ListAppointmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointments  []*Appointment         `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsResponse) Reset() {
	*x = ListAppointmentsResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsResponse) ProtoMessage() {}

func (x *ListAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *ListAppointmentsResponse) GetAppointments() []*Appointment {
	if x != nil {
		return x.Appointments
	}
	return nil
}

type DeleteAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppointmentRequest) Reset() {
	*x = DeleteAppointmentRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppointmentRequest) ProtoMessage() {}

func (x *DeleteAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppointmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAppointmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppointmentResponse) Reset() {
	*x = DeleteAppointmentResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppointmentResponse) ProtoMessage() {}

func (x *DeleteAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppointmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{5}
}

type SubscribeAppointmentUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeAppointmentUpdatesRequest) Reset() {
	*x = SubscribeAppointmentUpdatesRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAppointmentUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAppointmentUpdatesRequest) ProtoMessage() {}

func (x *SubscribeAppointmentUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAppointmentUpdatesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeAppointmentUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{6}
}

type AppointmentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId string                 `protobuf:"bytes,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`           // "created" | "deleted"
	Appointment   *Appointment           `protobuf:"bytes,3,opt,name=appointment,proto3" json:"appointment,omitempty"` // full appointment for created; empty for deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppointmentEvent) Reset() {
	*x = AppointmentEvent{}
	mi := &file_proto_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentEvent) ProtoMessage() {}

func (x *AppointmentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentEvent.ProtoReflect.Descriptor instead.
func (*AppointmentEvent) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *AppointmentEvent) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

func (x *AppointmentEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AppointmentEvent) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

var File_proto_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x15proto/scheduler.proto\x12\fscheduler.v1\"\xf6\x01\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\tR\bdoctorId\x12\x1f\n" +
	"\vdoctor_name\x18\x03 \x01(\tR\n" +
	"doctorName\x12&\n" +
	"\x0fstart_time_unix\x18\x04 \x01(\x03R\rstartTimeUnix\x12%\n" +
	"\x0eduration_slots\x18\x05 \x01(\x05R\rdurationSlots\x12!\n" +
	"\fpatient_name\x18\x06 \x01(\tR\vpatientName\x12'\n" +
	"\x0fpatient_contact\x18\a \x01(\tR\x0epatientContact\"\xf3\x01\n" +
	"\x18CreateAppointmentRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\tR\bdoctorId\x12\x1f\n" +
	"\vdoctor_name\x18\x02 \x01(\tR\n" +
	"doctorName\x12&\n" +
	"\x0fstart_time_unix\x18\x03 \x01(\x03R\rstartTimeUnix\x12%\n" +
	"\x0eduration_slots\x18\x04 \x01(\x05R\rdurationSlots\x12!\n" +
	"\fpatient_name\x18\x05 \x01(\tR\vpatientName\x12'\n" +
	"\x0fpatient_contact\x18\x06 \x01(\tR\x0epatientContact\"a\n" +
	"\x17ListAppointmentsRequest\x12$\n" +
	"\x0efrom_time_unix\x18\x01 \x01(\x03R\ffromTimeUnix\x12 \n" +
	"\fto_time_unix\x18\x02 \x01(\x03R\n" +
	"toTimeUnix\"Y\n" +
	"\x18ListAppointmentsResponse\x12=\n" +
	"\fappointments\x18\x01 \x03(\v2\x19.scheduler.v1.AppointmentR\fappointments\"*\n" +
	"\x18DeleteAppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19DeleteAppointmentResponse\"$\n" +
	"\"SubscribeAppointmentUpdatesRequest\"\x8e\x01\n" +
	"\x10AppointmentEvent\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\tR\rappointmentId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12;\n" +
	"\vappointment\x18\x03 \x01(\v2\x19.scheduler.v1.AppointmentR\vappointment2\xa6\x03\n" +
	"\x10SchedulerService\x12V\n" +
	"\x11CreateAppointment\x12&.scheduler.v1.CreateAppointmentRequest\x1a\x19.scheduler.v1.Appointment\x12a\n" +
	"\x10ListAppointments\x12%.scheduler.v1.ListAppointmentsRequest\x1a&.scheduler.v1.ListAppointmentsResponse\x12d\n" +
	"\x11DeleteAppointment\x12&.scheduler.v1.DeleteAppointmentRequest\x1a'.scheduler.v1.DeleteAppointmentResponse\x12q\n" +
	"\x1bSubscribeAppointmentUpdates\x120.scheduler.v1.SubscribeAppointmentUpdatesRequest\x1a\x1e.scheduler.v1.AppointmentEvent0\x01B#Z!scheduler/backend/gen/schedulerv1b\x06proto3"

var (
	file_proto_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_proto_rawDescData
}

var file_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_scheduler_proto_goTypes = []any{
	(*Appointment)(nil),                        // 0: scheduler.v1.Appointment
	(*CreateAppointmentRequest)(nil),           // 1: scheduler.v1.CreateAppointmentRequest
	(*ListAppointmentsRequest)(nil),            // 2: scheduler.v1.ListAppointmentsRequest
	(*ListAppointmentsResponse)(nil),           // 3: scheduler.v1.ListAppointmentsResponse
	(*DeleteAppointmentRequest)(nil),           // 4: scheduler.v1.DeleteAppointmentRequest
	(*DeleteAppointmentResponse)(nil),          // 5: scheduler.v1.DeleteAppointmentResponse
	(*SubscribeAppointmentUpdatesRequest)(nil), // 6: scheduler.v1.SubscribeAppointmentUpdatesRequest
	(*AppointmentEvent)(nil),                   // 7: scheduler.v1.AppointmentEvent
}
var file_proto_scheduler_proto_depIdxs = []int32{
	0, // 0: scheduler.v1.ListAppointmentsResponse.appointments:type_name -> scheduler.v1.Appointment
	0, // 1: scheduler.v1.AppointmentEvent.appointment:type_name -> scheduler.v1.Appointment
	1, // 2: scheduler.v1.SchedulerService.CreateAppointment:input_type -> scheduler.v1.CreateAppointmentRequest
	2, // 3: scheduler.v1.SchedulerService.ListAppointments:input_type -> scheduler.v1.ListAppointmentsRequest
	4, // 4: scheduler.v1.SchedulerService.DeleteAppointment:input_type -> scheduler.v1.DeleteAppointmentRequest
	6, // 5: scheduler.v1.SchedulerService.SubscribeAppointmentUpdates:input_type -> scheduler.v1.SubscribeAppointmentUpdatesRequest
	0, // 6: scheduler.v1.SchedulerService.CreateAppointment:output_type -> scheduler.v1.Appointment
	3, // 7: scheduler.v1.SchedulerService.ListAppointments:output_type -> scheduler.v1.ListAppointmentsResponse
	5, // 8: scheduler.v1.SchedulerService.DeleteAppointment:output_type -> scheduler.v1.DeleteAppointmentResponse
	7, // 9: scheduler.v1.SchedulerService.SubscribeAppointmentUpdates:output_type -> scheduler.v1.AppointmentEvent
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_scheduler_proto_init() }
func file_proto_scheduler_proto_init() {
	if File_proto_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_proto_depIdxs,
		MessageInfos:      file_proto_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_proto = out.File
	file_proto_scheduler_proto_goTypes = nil
	file_proto_scheduler_proto_depIdxs = nil
}
